### PR TITLE
fix/ci: add fuzz and flamegraph jobs for PRs

### PR DESCRIPTION
**Pull request by drahnr**
Goals of this PR are that from now on each and every PR

* [x] is fuzzed with `n` iterations of fuzzing to assure no new errors are introduced
* [x] comments with a flamegraph of the test run
* [ ] automatically exhibits performance changes compared to master

(also acts as a initial bug squeching guinnea pig so most tooling edge cases are resolved before tackling smth bigger)

### CODE REVIEW

**Comment by sirmergealot** [comment]
Flamegraph could not be created :sad:

**Comment by sirmergealot** [comment]
Flamegraph could not be created 💥

**Comment by sirmergealot** [comment]
Flamegraph could not be created 💥

**Comment by sirmergealot** [comment]
Flamegraph could not be created 💥

**Comment by sirmergealot** [comment]
Flamegraph is ready!

**Comment by sirmergealot** [comment]
<?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg version="1.1" width="1200" height="390" onload="init(evt)" viewBox="0 0 1200 390" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs><linearGradient id="background" y1="0" y2="1" x1="0" x2="0"><stop stop-color="#eeeeee" offset="5%"/><stop stop-color="#eeeeb0" offset="95%"/></linearGradient></defs><style type="text/css">
text { font-family:"Verdana"; font-size:12px; fill:rgb(0,0,0); }
#title { text-anchor:middle; font-size:17px; }
#search { opacity:0.1; cursor:pointer; }
#search:hover, #search.show { opacity:1; }
#subtitle { text-anchor:middle; font-color:rgb(160,160,160); }
#unzoom { cursor:pointer; }
#frames > *:hover { stroke:black; stroke-width:0.5; cursor:pointer; }
.hide { display:none; }
.parent { opacity:0.5; }
</style><script type="text/ecmascript"><![CDATA[var nametype = 'Function:';
var fontsize = 12;
var fontwidth = 0.59;
var xpad = 10;
var inverted = false;
var searchcolor = 'rgb(230,0,230)';
var fluiddrawing = true;
var truncate_text_right = false;]]><![CDATA["use strict";
var details, searchbtn, unzoombtn, matchedtxt, svg, searching, frames;
function init(evt) {
    details = document.getElementById("details").firstChild;
    searchbtn = document.getElementById("search");
    unzoombtn = document.getElementById("unzoom");
    matchedtxt = document.getElementById("matched");
    svg = document.getElementsByTagName("svg")[0];
    frames = document.getElementById("frames");
    searching = 0;

    // Use GET parameters to restore a flamegraph's state.
    var restore_state = function() {
        var params = get_params();
        if (params.x && params.y)
            zoom(find_group(document.querySelector('[x="' + params.x + '"][y="' + params.y + '"]')));
        if (params.s)
            search(params.s);
    };

    if (fluiddrawing) {
        // Make width dynamic so the SVG fits its parent's width.
        svg.removeAttribute("width");
        // Edge requires us to have a viewBox that gets updated with size changes.
        var isEdge = /Edge\/\d./i.test(navigator.userAgent);
        if (!isEdge) {
          svg.removeAttribute("viewBox");
        }
        var update_for_width_change = function() {
            if (isEdge) {
                svg.attributes.viewBox.value = "0 0 " + svg.width.baseVal.value + " " + svg.height.baseVal.value;
            }

            // Keep consistent padding on left and right of frames container.
            frames.attributes.width.value = svg.width.baseVal.value - xpad * 2;

            // Text truncation needs to be adjusted for the current width.
            var el = frames.children;
            for(var i = 0; i < el.length; i++) {
                update_text(el[i]);
            }

            // Keep search elements at a fixed distance from right edge.
            var svgWidth = svg.width.baseVal.value;
            searchbtn.attributes.x.value = svgWidth - xpad - 100;
            matchedtxt.attributes.x.value = svgWidth - xpad - 100;
        };
        window.addEventListener('resize', function() {
            update_for_width_change();
        });
        // This needs to be done asynchronously for Safari to work.
        setTimeout(function() {
            unzoom();
            update_for_width_change();
            restore_state();
        }, 0);
    } else {
        restore_state();
    }
}
// event listeners
window.addEventListener("click", function(e) {
    var target = find_group(e.target);
    if (target) {
        if (target.nodeName == "a") {
            if (e.ctrlKey === false) return;
            e.preventDefault();
        }
        if (target.classList.contains("parent")) unzoom();
        zoom(target);

        // set parameters for zoom state
        var el = target.querySelector("rect");
        if (el && el.attributes && el.attributes.y && el.attributes._orig_x) {
            var params = get_params()
            params.x = el.attributes._orig_x.value;
            params.y = el.attributes.y.value;
            history.replaceState(null, null, parse_params(params));
        }
    }
    else if (e.target.id == "unzoom") {
        unzoom();

        // remove zoom state
        var params = get_params();
        if (params.x) delete params.x;
        if (params.y) delete params.y;
        history.replaceState(null, null, parse_params(params));
    }
    else if (e.target.id == "search") search_prompt();
}, false)
// mouse-over for info
// show
window.addEventListener("mouseover", function(e) {
    var target = find_group(e.target);
    if (target) details.nodeValue = nametype + " " + g_to_text(target);
}, false)
// clear
window.addEventListener("mouseout", function(e) {
    var target = find_group(e.target);
    if (target) details.nodeValue = ' ';
}, false)
// ctrl-F for search
window.addEventListener("keydown",function (e) {
    if (e.keyCode === 114 || (e.ctrlKey && e.keyCode === 70)) {
        e.preventDefault();
        search_prompt();
    }
}, false)
// functions
function get_params() {
    var params = {};
    var paramsarr = window.location.search.substr(1).split('&');
    for (var i = 0; i < paramsarr.length; ++i) {
        var tmp = paramsarr[i].split("=");
        if (!tmp[0] || !tmp[1]) continue;
        params[tmp[0]]  = decodeURIComponent(tmp[1]);
    }
    return params;
}
function parse_params(params) {
    var uri = "?";
    for (var key in params) {
        uri += key + '=' + encodeURIComponent(params[key]) + '&';
    }
    if (uri.slice(-1) == "&")
        uri = uri.substring(0, uri.length - 1);
    if (uri == '?')
        uri = window.location.href.split('?')[0];
    return uri;
}
function find_child(node, selector) {
    var children = node.querySelectorAll(selector);
    if (children.length) return children[0];
    return;
}
function find_group(node) {
    var parent = node.parentElement;
    if (!parent) return;
    if (parent.id == "frames") return node;
    return find_group(parent);
}
function orig_save(e, attr, val) {
    if (e.attributes["_orig_" + attr] != undefined) return;
    if (e.attributes[attr] == undefined) return;
    if (val == undefined) val = e.attributes[attr].value;
    e.setAttribute("_orig_" + attr, val);
}
function orig_load(e, attr) {
    if (e.attributes["_orig_"+attr] == undefined) return;
    e.attributes[attr].value = e.attributes["_orig_" + attr].value;
    e.removeAttribute("_orig_" + attr);
}
function g_to_text(e) {
    var text = find_child(e, "title").firstChild.nodeValue;
    return (text)
}
function g_to_func(e) {
    var func = g_to_text(e);
    // if there's any manipulation we want to do to the function
    // name before it's searched, do it here before returning.
    return (func);
}
function update_text(e) {
    var r = find_child(e, "rect");
    var t = find_child(e, "text");
    var w = parseFloat(r.attributes.width.value) * frames.attributes.width.value / 100 - 3;
    var txt = find_child(e, "title").textContent.replace(/\([^(]*\)$/,"");
    t.attributes.x.value = format_percent((parseFloat(r.attributes.x.value) + (100 * 3 / frames.attributes.width.value)));
    // Smaller than this size won't fit anything
    if (w < 2 * fontsize * fontwidth) {
        t.textContent = "";
        return;
    }
    t.textContent = txt;
    // Fit in full text width
    if (/^ *\$/.test(txt) || t.getComputedTextLength() < w)
        return;
    if (truncate_text_right) {
        // Truncate the right side of the text.
        for (var x = txt.length - 2; x > 0; x--) {
            if (t.getSubStringLength(0, x + 2) <= w) {
                t.textContent = txt.substring(0, x) + "..";
                return;
            }
        }
    } else {
        // Truncate the left side of the text.
        for (var x = 2; x < txt.length; x++) {
            if (t.getSubStringLength(x - 2, txt.length) <= w) {
                t.textContent = ".." + txt.substring(x, txt.length);
                return;
            }
        }
    }
    t.textContent = "";
}
// zoom
function zoom_reset(e) {
    if (e.attributes != undefined) {
        orig_load(e, "x");
        orig_load(e, "width");
    }
    if (e.childNodes == undefined) return;
    for(var i = 0, c = e.childNodes; i < c.length; i++) {
        zoom_reset(c[i]);
    }
}
function zoom_child(e, x, ratio) {
    if (e.attributes != undefined) {
        if (e.attributes.x != undefined) {
            orig_save(e, "x");
            e.attributes.x.value = format_percent((parseFloat(e.attributes.x.value) - x) * ratio);
            if (e.tagName == "text") {
                e.attributes.x.value = format_percent(parseFloat(find_child(e.parentNode, "rect[x]").attributes.x.value) + (100 * 3 / frames.attributes.width.value));
            }
        }
        if (e.attributes.width != undefined) {
            orig_save(e, "width");
            e.attributes.width.value = format_percent(parseFloat(e.attributes.width.value) * ratio);
        }
    }
    if (e.childNodes == undefined) return;
    for(var i = 0, c = e.childNodes; i < c.length; i++) {
        zoom_child(c[i], x, ratio);
    }
}
function zoom_parent(e) {
    if (e.attributes) {
        if (e.attributes.x != undefined) {
            orig_save(e, "x");
            e.attributes.x.value = "0.0%";
        }
        if (e.attributes.width != undefined) {
            orig_save(e, "width");
            e.attributes.width.value = "100.0%";
        }
    }
    if (e.childNodes == undefined) return;
    for(var i = 0, c = e.childNodes; i < c.length; i++) {
        zoom_parent(c[i]);
    }
}
function zoom(node) {
    var attr = find_child(node, "rect").attributes;
    var width = parseFloat(attr.width.value);
    var xmin = parseFloat(attr.x.value);
    var xmax = xmin + width;
    var ymin = parseFloat(attr.y.value);
    var ratio = 100 / width;
    // XXX: Workaround for JavaScript float issues (fix me)
    var fudge = 0.001;
    unzoombtn.classList.remove("hide");
    var el = frames.children;
    for (var i = 0; i < el.length; i++) {
        var e = el[i];
        var a = find_child(e, "rect").attributes;
        var ex = parseFloat(a.x.value);
        var ew = parseFloat(a.width.value);
        // Is it an ancestor
        if (!inverted) {
            var upstack = parseFloat(a.y.value) > ymin;
        } else {
            var upstack = parseFloat(a.y.value) < ymin;
        }
        if (upstack) {
            // Direct ancestor
            if (ex <= xmin && (ex+ew+fudge) >= xmax) {
                e.classList.add("parent");
                zoom_parent(e);
                update_text(e);
            }
            // not in current path
            else
                e.classList.add("hide");
        }
        // Children maybe
        else {
            // no common path
            if (ex < xmin || ex + fudge >= xmax) {
                e.classList.add("hide");
            }
            else {
                zoom_child(e, xmin, ratio);
                update_text(e);
            }
        }
    }
}
function unzoom() {
    unzoombtn.classList.add("hide");
    var el = frames.children;
    for(var i = 0; i < el.length; i++) {
        el[i].classList.remove("parent");
        el[i].classList.remove("hide");
        zoom_reset(el[i]);
        update_text(el[i]);
    }
}
// search
function reset_search() {
    var el = document.querySelectorAll("#frames rect");
    for (var i = 0; i < el.length; i++) {
        orig_load(el[i], "fill")
    }
    var params = get_params();
    delete params.s;
    history.replaceState(null, null, parse_params(params));
}
function search_prompt() {
    if (!searching) {
        var term = prompt("Enter a search term (regexp " +
            "allowed, eg: ^ext4_)", "");
        if (term != null) {
            search(term)
        }
    } else {
        reset_search();
        searching = 0;
        searchbtn.classList.remove("show");
        searchbtn.firstChild.nodeValue = "Search"
        matchedtxt.classList.add("hide");
        matchedtxt.firstChild.nodeValue = ""
    }
}
function search(term) {
    var re = new RegExp(term);
    var el = frames.children;
    var matches = new Object();
    var maxwidth = 0;
    for (var i = 0; i < el.length; i++) {
        var e = el[i];
        var func = g_to_func(e);
        var rect = find_child(e, "rect");
        if (func == null || rect == null)
            continue;
        // Save max width. Only works as we have a root frame
        var w = parseFloat(rect.attributes.width.value);
        if (w > maxwidth)
            maxwidth = w;
        if (func.match(re)) {
            // highlight
            var x = parseFloat(rect.attributes.x.value);
            orig_save(rect, "fill");
            rect.attributes.fill.value = searchcolor;
            // remember matches
            if (matches[x] == undefined) {
                matches[x] = w;
            } else {
                if (w > matches[x]) {
                    // overwrite with parent
                    matches[x] = w;
                }
            }
            searching = 1;
        }
    }
    if (!searching)
        return;
    var params = get_params();
    params.s = term;
    history.replaceState(null, null, parse_params(params));

    searchbtn.classList.add("show");
    searchbtn.firstChild.nodeValue = "Reset Search";
    // calculate percent matched, excluding vertical overlap
    var count = 0;
    var lastx = -1;
    var lastw = 0;
    var keys = Array();
    for (k in matches) {
        if (matches.hasOwnProperty(k))
            keys.push(k);
    }
    // sort the matched frames by their x location
    // ascending, then width descending
    keys.sort(function(a, b){
        return a - b;
    });
    // Step through frames saving only the biggest bottom-up frames
    // thanks to the sort order. This relies on the tree property
    // where children are always smaller than their parents.
    var fudge = 0.0001;    // JavaScript floating point
    for (var k in keys) {
        var x = parseFloat(keys[k]);
        var w = matches[keys[k]];
        if (x >= lastx + lastw - fudge) {
            count += w;
            lastx = x;
            lastw = w;
        }
    }
    // display matched percent
    matchedtxt.classList.remove("hide");
    var pct = 100 * count / maxwidth;
    if (pct != 100) pct = pct.toFixed(1);
    matchedtxt.firstChild.nodeValue = "Matched: " + pct + "%";
}
function format_percent(n) {
    return n.toFixed(4) + "%";
}
]]></script><rect x="0" y="0" width="100%" height="390" fill="url(#background)"/><text id="title" x="50.0000%" y="24.00">Flame Graph</text><text id="details" x="10" y="373.00"> </text><text id="unzoom" class="hide" x="10" y="24.00">Reset Zoom</text><text id="search" x="1090" y="24.00">Search</text><text id="matched" x="1090" y="373.00"> </text><svg id="frames" x="10" width="1180"><g><title>perf (5 samples, 62.50%)</title><rect x="0.0000%" y="325" width="62.5000%" height="15" fill="rgb(227,0,7)"/><text x="0.2500%" y="335.50">perf</text></g><g><title>entry_SYSCALL_64_after_hwframe (5 samples, 62.50%)</title><rect x="0.0000%" y="309" width="62.5000%" height="15" fill="rgb(217,0,24)"/><text x="0.2500%" y="319.50">entry_SYSCALL_64_after_hwframe</text></g><g><title>do_syscall_64 (5 samples, 62.50%)</title><rect x="0.0000%" y="293" width="62.5000%" height="15" fill="rgb(221,193,54)"/><text x="0.2500%" y="303.50">do_syscall_64</text></g><g><title>__x64_sys_execve (5 samples, 62.50%)</title><rect x="0.0000%" y="277" width="62.5000%" height="15" fill="rgb(248,212,6)"/><text x="0.2500%" y="287.50">__x64_sys_execve</text></g><g><title>do_execveat_common (5 samples, 62.50%)</title><rect x="0.0000%" y="261" width="62.5000%" height="15" fill="rgb(208,68,35)"/><text x="0.2500%" y="271.50">do_execveat_common</text></g><g><title>bprm_execve (5 samples, 62.50%)</title><rect x="0.0000%" y="245" width="62.5000%" height="15" fill="rgb(232,128,0)"/><text x="0.2500%" y="255.50">bprm_execve</text></g><g><title>load_elf_binary (5 samples, 62.50%)</title><rect x="0.0000%" y="229" width="62.5000%" height="15" fill="rgb(207,160,47)"/><text x="0.2500%" y="239.50">load_elf_binary</text></g><g><title>begin_new_exec (5 samples, 62.50%)</title><rect x="0.0000%" y="213" width="62.5000%" height="15" fill="rgb(228,23,34)"/><text x="0.2500%" y="223.50">begin_new_exec</text></g><g><title>perf_event_exec (5 samples, 62.50%)</title><rect x="0.0000%" y="197" width="62.5000%" height="15" fill="rgb(218,30,26)"/><text x="0.2500%" y="207.50">perf_event_exec</text></g><g><title>__intel_pmu_enable_all.constprop.0 (5 samples, 62.50%)</title><rect x="0.0000%" y="181" width="62.5000%" height="15" fill="rgb(220,122,19)"/><text x="0.2500%" y="191.50">__intel_pmu_enable_all.constprop.0</text></g><g><title>native_write_msr (5 samples, 62.50%)</title><rect x="0.0000%" y="165" width="62.5000%" height="15" fill="rgb(250,228,42)"/><text x="0.2500%" y="175.50">native_write_msr</text></g><g><title>.annobin_rtld.c (1 samples, 12.50%)</title><rect x="62.5000%" y="309" width="12.5000%" height="15" fill="rgb(240,193,28)"/><text x="62.7500%" y="319.50">.annobin_rtld.c</text></g><g><title>_dl_start (1 samples, 12.50%)</title><rect x="62.5000%" y="293" width="12.5000%" height="15" fill="rgb(216,20,37)"/><text x="62.7500%" y="303.50">_dl_start</text></g><g><title>_dl_sysdep_start (1 samples, 12.50%)</title><rect x="62.5000%" y="277" width="12.5000%" height="15" fill="rgb(206,188,39)"/><text x="62.7500%" y="287.50">_dl_sysdep_start</text></g><g><title>dl_main (1 samples, 12.50%)</title><rect x="62.5000%" y="261" width="12.5000%" height="15" fill="rgb(217,207,13)"/><text x="62.7500%" y="271.50">dl_main</text></g><g><title>_dl_map_object_deps (1 samples, 12.50%)</title><rect x="62.5000%" y="245" width="12.5000%" height="15" fill="rgb(231,73,38)"/><text x="62.7500%" y="255.50">_dl_map_object_deps</text></g><g><title>_dl_catch_exception (1 samples, 12.50%)</title><rect x="62.5000%" y="229" width="12.5000%" height="15" fill="rgb(225,20,46)"/><text x="62.7500%" y="239.50">_dl_catch_exception</text></g><g><title>openaux (1 samples, 12.50%)</title><rect x="62.5000%" y="213" width="12.5000%" height="15" fill="rgb(210,31,41)"/><text x="62.7500%" y="223.50">openaux</text></g><g><title>_dl_map_object (1 samples, 12.50%)</title><rect x="62.5000%" y="197" width="12.5000%" height="15" fill="rgb(221,200,47)"/><text x="62.7500%" y="207.50">_dl_map_object</text></g><g><title>_dl_map_object_from_fd (1 samples, 12.50%)</title><rect x="62.5000%" y="181" width="12.5000%" height="15" fill="rgb(226,26,5)"/><text x="62.7500%" y="191.50">_dl_map_object_from..</text></g><g><title>__mmap (1 samples, 12.50%)</title><rect x="62.5000%" y="165" width="12.5000%" height="15" fill="rgb(249,33,26)"/><text x="62.7500%" y="175.50">__mmap</text></g><g><title>entry_SYSCALL_64_after_hwframe (1 samples, 12.50%)</title><rect x="62.5000%" y="149" width="12.5000%" height="15" fill="rgb(235,183,28)"/><text x="62.7500%" y="159.50">entry_SYSCALL_64_af..</text></g><g><title>do_syscall_64 (1 samples, 12.50%)</title><rect x="62.5000%" y="133" width="12.5000%" height="15" fill="rgb(221,5,38)"/><text x="62.7500%" y="143.50">do_syscall_64</text></g><g><title>ksys_mmap_pgoff (1 samples, 12.50%)</title><rect x="62.5000%" y="117" width="12.5000%" height="15" fill="rgb(247,18,42)"/><text x="62.7500%" y="127.50">ksys_mmap_pgoff</text></g><g><title>vm_mmap_pgoff (1 samples, 12.50%)</title><rect x="62.5000%" y="101" width="12.5000%" height="15" fill="rgb(241,131,45)"/><text x="62.7500%" y="111.50">vm_mmap_pgoff</text></g><g><title>do_mmap (1 samples, 12.50%)</title><rect x="62.5000%" y="85" width="12.5000%" height="15" fill="rgb(249,31,29)"/><text x="62.7500%" y="95.50">do_mmap</text></g><g><title>mmap_region (1 samples, 12.50%)</title><rect x="62.5000%" y="69" width="12.5000%" height="15" fill="rgb(225,111,53)"/><text x="62.7500%" y="79.50">mmap_region</text></g><g><title>__do_munmap (1 samples, 12.50%)</title><rect x="62.5000%" y="53" width="12.5000%" height="15" fill="rgb(238,160,17)"/><text x="62.7500%" y="63.50">__do_munmap</text></g><g><title>__vma_rb_erase (1 samples, 12.50%)</title><rect x="62.5000%" y="37" width="12.5000%" height="15" fill="rgb(214,148,48)"/><text x="62.7500%" y="47.50">__vma_rb_erase</text></g><g><title>entry_SYSCALL_64_after_hwframe (1 samples, 12.50%)</title><rect x="75.0000%" y="309" width="12.5000%" height="15" fill="rgb(232,36,49)"/><text x="75.2500%" y="319.50">entry_SYSCALL_64_af..</text></g><g><title>do_syscall_64 (1 samples, 12.50%)</title><rect x="75.0000%" y="293" width="12.5000%" height="15" fill="rgb(209,103,24)"/><text x="75.2500%" y="303.50">do_syscall_64</text></g><g><title>__x64_sys_execve (1 samples, 12.50%)</title><rect x="75.0000%" y="277" width="12.5000%" height="15" fill="rgb(229,88,8)"/><text x="75.2500%" y="287.50">__x64_sys_execve</text></g><g><title>do_execveat_common (1 samples, 12.50%)</title><rect x="75.0000%" y="261" width="12.5000%" height="15" fill="rgb(213,181,19)"/><text x="75.2500%" y="271.50">do_execveat_common</text></g><g><title>bprm_execve (1 samples, 12.50%)</title><rect x="75.0000%" y="245" width="12.5000%" height="15" fill="rgb(254,191,54)"/><text x="75.2500%" y="255.50">bprm_execve</text></g><g><title>load_elf_binary (1 samples, 12.50%)</title><rect x="75.0000%" y="229" width="12.5000%" height="15" fill="rgb(241,83,37)"/><text x="75.2500%" y="239.50">load_elf_binary</text></g><g><title>setup_arg_pages (1 samples, 12.50%)</title><rect x="75.0000%" y="213" width="12.5000%" height="15" fill="rgb(233,36,39)"/><text x="75.2500%" y="223.50">setup_arg_pages</text></g><g><title>mprotect_fixup (1 samples, 12.50%)</title><rect x="75.0000%" y="197" width="12.5000%" height="15" fill="rgb(226,3,54)"/><text x="75.2500%" y="207.50">mprotect_fixup</text></g><g><title>perf_event_mmap (1 samples, 12.50%)</title><rect x="75.0000%" y="181" width="12.5000%" height="15" fill="rgb(245,192,40)"/><text x="75.2500%" y="191.50">perf_event_mmap</text></g><g><title>perf_iterate_sb (1 samples, 12.50%)</title><rect x="75.0000%" y="165" width="12.5000%" height="15" fill="rgb(238,167,29)"/><text x="75.2500%" y="175.50">perf_iterate_sb</text></g><g><title>perf_event_mmap_output (1 samples, 12.50%)</title><rect x="75.0000%" y="149" width="12.5000%" height="15" fill="rgb(232,182,51)"/><text x="75.2500%" y="159.50">perf_event_mmap_out..</text></g><g><title>all (8 samples, 100%)</title><rect x="0.0000%" y="341" width="100.0000%" height="15" fill="rgb(231,60,39)"/><text x="0.2500%" y="351.50"></text></g><g><title>reed-solomon-be (3 samples, 37.50%)</title><rect x="62.5000%" y="325" width="37.5000%" height="15" fill="rgb(208,69,12)"/><text x="62.7500%" y="335.50">reed-solomon-be</text></g><g><title>reed_solomon_novelpoly::novel_poly_basis::ReedSolomon::reconstruct (1 samples, 12.50%)</title><rect x="87.5000%" y="309" width="12.5000%" height="15" fill="rgb(235,93,37)"/><text x="87.7500%" y="319.50">reed_solomon_novelp..</text></g><g><title>reed_solomon_novelpoly::field::f2e16::eval_error_polynomial (1 samples, 12.50%)</title><rect x="87.5000%" y="293" width="12.5000%" height="15" fill="rgb(213,116,39)"/><text x="87.7500%" y="303.50">reed_solomon_novelp..</text></g><g><title>reed_solomon_novelpoly::field::f2e16::walsh (1 samples, 12.50%)</title><rect x="87.5000%" y="277" width="12.5000%" height="15" fill="rgb(222,207,29)"/><text x="87.7500%" y="287.50">reed_solomon_novelp..</text></g></svg></svg>

**Comment by sirmergealot** [comment]
Flamegraph could not be created 💥

**Comment by sirmergealot** [comment]
Flamegraph could not be created 💥

**Comment by sirmergealot** [comment]
Flamegraph could not be created 💥

**Comment by sirmergealot** [comment]
Flamegraph could not be created 💥

**Comment by sirmergealot** [comment]
Flamegraph could not be created 💥

**Comment by sirmergealot** [comment]
Flamegraph could not be created 🐞

**Comment by sirmergealot** [comment]
[🔥 flamegraph 🔥](https://minio.spearow.io/reed-solomon-flamegraph/flamegraph-d3c785da9040687e0bca7dcff5504ed2b91989e7.svg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=U3SW6059ITW4NFW5KR43%2F20210421%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210421T151213Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=49394283e0e3d5e561738e562a0bdd44214733cae47e2f93ca1f58336f0bcde7)

**Comment by sirmergealot** [comment]
[🔥 flamegraph 🔥](https://minio.spearow.io/reed-solomon-flamegraph/flamegraph-1c40a95feae548273ce0448d9958bd24a4261db8.svg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=U3SW6059ITW4NFW5KR43%2F20210421%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210421T152118Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=fe42f8d79ec658556ddf505ed030778b8ff6124d4b580d79d927869ff70d518c)

**Comment by sirmergealot** [comment]
Flamegraph could not be created 🐞

**Comment by sirmergealot** [comment]
[🔥 flamegraph 🔥](https://minio.spearow.io/reed-solomon-flamegraph/flamegraph-1c40a95feae548273ce0448d9958bd24a4261db8.svg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=U3SW6059ITW4NFW5KR43%2F20210422%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210422T132623Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=1495fff42aa4e7dc67c952c5d6bd0a6592ede9a642e417ca3bb0fb25fb4dc4a6)

**Comment by sirmergealot** [comment]
Flamegraph could not be created 🐞

**Comment by drahnr** [comment]
The generated flamegraphs are still garbage, assuming some seccomp filters prevent a bunch of syscalls to gather more metrics.

**Comment by sirmergealot** [comment]
[🔥 flamegraph 🔥](https://minio.spearow.io/reed-solomon-flamegraph/flamegraph-1c40a95feae548273ce0448d9958bd24a4261db8.svg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=U3SW6059ITW4NFW5KR43%2F20210422%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210422T133822Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=a9cfcea8cdbc761ba08424a992811c4a5208eedabfd3e821652545d4b7a3bd3f)

**Comment by sirmergealot** [comment]
[🔥 flamegraph 🔥](https://minio.spearow.io/reed-solomon-flamegraph/flamegraph-199bfb72190a7929e5e986a05ad905c580e4b256.svg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=U3SW6059ITW4NFW5KR43%2F20210422%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210422T135424Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=a06c69cc0e9e73690d507d4de13283acda1b91026695539bd839016d1ef9d4ad)

**Comment by sirmergealot** [comment]
[🔥 flamegraph 🔥](https://minio.spearow.io/reed-solomon-flamegraph/flamegraph-9187839c5cf2b1b294c94738ec52c4bf088a9641.svg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=U3SW6059ITW4NFW5KR43%2F20210422%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210422T135837Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=e0afb5b0b012c16949b504d57b50eb311639ae818905c363a01b9199fbbe9a4d)

**Comment by sirmergealot** [comment]
[🔥 flamegraph 🔥](https://minio.spearow.io/reed-solomon-flamegraph/flamegraph-9187839c5cf2b1b294c94738ec52c4bf088a9641.svg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=U3SW6059ITW4NFW5KR43%2F20210422%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210422T140602Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=e0ecbe42919d196afdeccb1e06ac908935169379673063001432558e9293f7e2)

**Pull request merged**
